Repository socolorphil/RateMyLandlord, pull requests merged in 2021-02, with the labels that each got.

#5 Created Basic Navigation
  App.js
  components/navigation/StackNavigator.js
  components/navigation/TabNavigator.js
  components/screens/HomeScreen.js
  package-lock.json
  package.json
Labels: Feature, UI

#6 New docs
  README.md
Labels: Small changes

#9 Backend
  .gitignore
  backend/.gitignore
  backend/config/db.js
  backend/index.js
  backend/models/Manager.js
  backend/models/Profile.js
  backend/package-lock.json
  backend/package.json
  backend/routes/managers.js
Labels: Database
